export const SUPPORTED_LANGUAGES = {
  en: 'English',
  es: 'Spanish',
  de: 'Deutsch',
  fr: 'French',
  it: 'Italian',
  ja: 'Japanese',
  zh: 'Chinese',
  ar: 'Arabic',
  pt: 'Portuguese',
  ru: 'Russian',
  hi: 'Hindi',
  ko: 'Korean',
  nl: 'Dutch',
  tr: 'Turkish',
  sv: 'Swedish',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  el: 'Greek',
  pl: 'Polish',
  he: 'Hebrew',
  th: 'Thai',
  id: 'Indonesian',
  cs: 'Czech',
  hu: 'Hungarian',
  ro: 'Romanian',
  vi: 'Vietnamese',
  uk: 'Ukrainian'
}

export const AUTO_LANGUAGE = 'auto'
